Page({
    data:{
        content:[
            {
                name:"野生动物相关的讯息",
                url:"../../res/huanan.webp",
                from:"赛博森林",
                vis:false
            },
            {
                name:"野生动物相关的讯息",
                url:"../../res/huanan.webp",
                from:"赛博森林",
                vis:true
            },
            {
                name:"野生动物相关的讯息",
                url:"../../res/huanan.webp",
                from:"赛博森林",
                vis:false
            },
            {
                name:"野生动物相关的讯息",
                url:"../../res/huanan.webp",
                from:"赛博森林",
                vis:true
            },
            {
                name:"野生动物相关的讯息",
                url:"../../res/huanan.webp",
                from:"赛博森林",
                vis:false
            },
        ]
    }
})